# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='race',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='gender',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
