# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_auto_20160323_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='race',
        ),
    ]
